version: "3.7"
services:
  nginx:
    build: "./.docker/nginx"
    ports:
      - "80:80"
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./app/web:/web"
    depends_on:
      - app

  app:
    build: "./.docker/php"
    working_dir: "/app"
    volumes:
      - ".:/mini-blog"
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - mysql

  mysql:
    build: "./.docker/mysql"
    ports:
      - "3306:3306"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-php}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    links:
      - "mysql:db"
    ports:
      - "9090:80"
